#!/bin/bash


# Compile Core

cat Core/Core.js > Fit.UI.js
cat Core/Validation.js >> Fit.UI.js
cat Core/Styles.css > Fit.UI.css
#cat Resources/FontAwesome/css/font-awesome.min.css >> Fit.UI.css
cat Resources/FontAwesome/css/font-awesome.css >> Fit.UI.css

for file in `ls Core/*js | grep -v Core/Core.js | grep -v Core/Validation.js | grep -v Core/json2.js`
do
	cat $file >> Fit.UI.js
done


# Compile UI controls

for dir in `ls Controls`
do
	for file in `ls Controls/$dir/ | grep .js`
	do
		cat Controls/$dir/$file >> Fit.UI.js
	done

	for file in `ls Controls/$dir/ | grep .css`
	do
		cat Controls/$dir/$file >> Fit.UI.css
	done
done


# Create dist

rm dist/ -R

mkdir dist
mkdir -p dist/Controls/TreeView

cp Fit.UI.js dist/
cp Fit.UI.css dist/
cp Controls/TreeView/*.png dist/Controls/TreeView
cp Resources/ dist/ -R

cp Examples/ dist/ -R

zip -r dist-$(date +%F) dist
